// ===== BEGINNER 2 APPROVED MCQ QUESTIONS (46 Questions) =====
// Filtered according to feedback from Questions_100.xlsx

const BEGINNER2_MCQ = [
  {
    "num": 1,
    "origNum": 1,
    "category": "Grammar",
    "unit": "7A",
    "topic": "this/that/these/those",
    "q": "Complete: \"I like _______ plant.\" (pointing to a plant near you)",
    "a": "this",
    "b": "that",
    "c": "these",
    "d": "those",
    "ans": "A"
  },
  {
    "num": 2,
    "origNum": 2,
    "category": "Grammar",
    "unit": "7A",
    "topic": "this/that/these/those",
    "q": "Complete: \"Oh, look at _______ chairs over there. They're really nice.\"",
    "a": "this",
    "b": "that",
    "c": "these",
    "d": "those",
    "ans": "D"
  },
  {
    "num": 3,
    "origNum": 3,
    "category": "Grammar",
    "unit": "7A",
    "topic": "this/that/these/those",
    "q": "Which word is used for a singular object far from the speaker?",
    "a": "this",
    "b": "that",
    "c": "these",
    "d": "those",
    "ans": "B"
  },
  {
    "num": 4,
    "origNum": 4,
    "category": "Grammar",
    "unit": "7A",
    "topic": "this/that/these/those",
    "q": "Which word is used for plural objects near the speaker?",
    "a": "this",
    "b": "that",
    "c": "these",
    "d": "those",
    "ans": "C"
  },
  {
    "num": 5,
    "origNum": 5,
    "category": "Grammar",
    "unit": "7A",
    "topic": "this/that/these/those",
    "q": "\"_______ plates are beautiful!\" (pointing to plates far away)",
    "a": "This",
    "b": "That",
    "c": "These",
    "d": "Those",
    "ans": "D"
  },
  {
    "num": 6,
    "origNum": 6,
    "category": "Grammar",
    "unit": "7A",
    "topic": "this/that/these/those",
    "q": "\"Look at _______ speaker! That's so cool.\" (pointing to a speaker far away)",
    "a": "this",
    "b": "that",
    "c": "these",
    "d": "those",
    "ans": "B"
  },
  {
    "num": 7,
    "origNum": 9,
    "category": "Vocabulary",
    "unit": "7A",
    "topic": "Prices",
    "q": "How do you correctly say \"£3.80\" in English?",
    "a": "three pound eighty",
    "b": "three pounds and eighty",
    "c": "three pounds eighty",
    "d": "three and eighty pounds",
    "ans": "C"
  },
  {
    "num": 8,
    "origNum": 12,
    "category": "Vocabulary",
    "unit": "7A",
    "topic": "Shopping",
    "q": "What time does Books & Co. open?",
    "a": "8 am",
    "b": "6 am",
    "c": "9 am",
    "d": "10 am",
    "ans": "C"
  },
  {
    "num": 9,
    "origNum": 13,
    "category": "Grammar",
    "unit": "7A",
    "topic": "this/that/these/those",
    "q": "\"_______ lamp is nice – it's a great colour!\" (holding a lamp near you)",
    "a": "This",
    "b": "That",
    "c": "These",
    "d": "Those",
    "ans": "A"
  },
  {
    "num": 10,
    "origNum": 14,
    "category": "Vocabulary",
    "unit": "7A",
    "topic": "Sounds/Spelling",
    "q": "Which word has the /b/ sound?",
    "a": "plate",
    "b": "guitar",
    "c": "bag",
    "d": "cup",
    "ans": "C"
  },
  {
    "num": 11,
    "origNum": 15,
    "category": "Grammar",
    "unit": "7B",
    "topic": "Possessive 's",
    "q": "\"Is this Greg's T-shirt?\" means:",
    "a": "The T-shirt belongs to Greg",
    "b": "Greg is a T-shirt",
    "c": "Greg bought a T-shirt for someone",
    "d": "The T-shirt is new",
    "ans": "A"
  },
  {
    "num": 12,
    "origNum": 16,
    "category": "Grammar",
    "unit": "7B",
    "topic": "Possessive 's",
    "q": "\"They're Kate's jeans.\" What does \"Kate's\" mean?",
    "a": "Kate is jeans",
    "b": "The jeans belong to Kate",
    "c": "Kate likes jeans",
    "d": "Kate sells jeans",
    "ans": "B"
  },
  {
    "num": 13,
    "origNum": 17,
    "category": "Grammar",
    "unit": "7B",
    "topic": "Adverbs of frequency",
    "q": "Which adverb means \"100% of the time\"?",
    "a": "sometimes",
    "b": "often",
    "c": "usually",
    "d": "always",
    "ans": "D"
  },
  {
    "num": 14,
    "origNum": 18,
    "category": "Grammar",
    "unit": "7B",
    "topic": "Adverbs of frequency",
    "q": "\"She wears a skirt (never).\" The correct sentence is:",
    "a": "She never wears a skirt.",
    "b": "She wears never a skirt.",
    "c": "Never she wears a skirt.",
    "d": "She wears a skirt never.",
    "ans": "A"
  },
  {
    "num": 15,
    "origNum": 19,
    "category": "Grammar",
    "unit": "7B",
    "topic": "Adverbs of frequency",
    "q": "\"Fran wears a dress (often).\" The correct sentence is:",
    "a": "Often Fran wears a dress.",
    "b": "Fran wears often a dress.",
    "c": "Fran often wears a dress.",
    "d": "Fran wears a dress often.",
    "ans": "C"
  },
  {
    "num": 16,
    "origNum": 21,
    "category": "Vocabulary",
    "unit": "7B",
    "topic": "Clothes",
    "q": "Tom Ford often wears a _______ shirt.",
    "a": "black",
    "b": "blue",
    "c": "white",
    "d": "red",
    "ans": "C"
  },
  {
    "num": 17,
    "origNum": 28,
    "category": "Grammar",
    "unit": "8A",
    "topic": "Past simple: be",
    "q": "Complete: \"I _______ in New York three days ago.\"",
    "a": "am",
    "b": "was",
    "c": "were",
    "d": "be",
    "ans": "B"
  },
  {
    "num": 18,
    "origNum": 29,
    "category": "Grammar",
    "unit": "8A",
    "topic": "Past simple: be",
    "q": "Complete: \"We _______ in Munich on Wednesday.\"",
    "a": "was",
    "b": "am",
    "c": "were",
    "d": "is",
    "ans": "C"
  },
  {
    "num": 19,
    "origNum": 30,
    "category": "Grammar",
    "unit": "8A",
    "topic": "Past simple: be",
    "q": "\"_______ you at work yesterday?\" Complete with the correct form.",
    "a": "Was",
    "b": "Were",
    "c": "Are",
    "d": "Is",
    "ans": "B"
  },
  {
    "num": 20,
    "origNum": 31,
    "category": "Grammar",
    "unit": "8A",
    "topic": "Past simple: be negative",
    "q": "\"It _______ a holiday for me.\" (negative)",
    "a": "wasn't",
    "b": "weren't",
    "c": "isn't",
    "d": "didn't",
    "ans": "A"
  },
  {
    "num": 21,
    "origNum": 32,
    "category": "Grammar",
    "unit": "8A",
    "topic": "Past simple: be negative",
    "q": "\"We _______ at the party last night.\" (negative)",
    "a": "wasn't",
    "b": "weren't",
    "c": "didn't",
    "d": "aren't",
    "ans": "B"
  },
  {
    "num": 22,
    "origNum": 33,
    "category": "Grammar",
    "unit": "8A",
    "topic": "Past simple: be",
    "q": "Which sentence is correct?",
    "a": "She were in Dublin.",
    "b": "They was at home.",
    "c": "He was at a meeting.",
    "d": "I were in London.",
    "ans": "C"
  },
  {
    "num": 23,
    "origNum": 34,
    "category": "Vocabulary",
    "unit": "8A",
    "topic": "Past time expressions",
    "q": "Which expression means \"the day before today\"?",
    "a": "last week",
    "b": "two days ago",
    "c": "yesterday",
    "d": "this morning",
    "ans": "C"
  },
  {
    "num": 24,
    "origNum": 35,
    "category": "Vocabulary",
    "unit": "8A",
    "topic": "Past time expressions",
    "q": "\"Two weeks _______\" – complete the expression.",
    "a": "before",
    "b": "ago",
    "c": "past",
    "d": "last",
    "ans": "B"
  },
  {
    "num": 25,
    "origNum": 39,
    "category": "Vocabulary",
    "unit": "8A",
    "topic": "Events",
    "q": "Ava was on tour with her _______.",
    "a": "football team",
    "b": "band",
    "c": "photography group",
    "d": "family",
    "ans": "B"
  },
  {
    "num": 26,
    "origNum": 40,
    "category": "Grammar",
    "unit": "8A",
    "topic": "Past simple: be",
    "q": "\"About 1,000 people _______ at our concert.\"",
    "a": "was",
    "b": "is",
    "c": "were",
    "d": "are",
    "ans": "C"
  },
  {
    "num": 27,
    "origNum": 41,
    "category": "Vocabulary",
    "unit": "8A",
    "topic": "Adjectives",
    "q": "Match: \"The meeting was _______.\" Which adjective is used in the text?",
    "a": "boring",
    "b": "interesting",
    "c": "exciting",
    "d": "fun",
    "ans": "B"
  },
  {
    "num": 28,
    "origNum": 42,
    "category": "Grammar",
    "unit": "8B",
    "topic": "Past simple: positive",
    "q": "\"He _______ a bear in the garden.\" Choose the correct past simple form.",
    "a": "see",
    "b": "sees",
    "c": "saw",
    "d": "seen",
    "ans": "C"
  },
  {
    "num": 29,
    "origNum": 43,
    "category": "Grammar",
    "unit": "8B",
    "topic": "Past simple: positive",
    "q": "\"She _______ into her living room and _______ TV.\"",
    "a": "go / watch",
    "b": "went / watched",
    "c": "goes / watches",
    "d": "going / watching",
    "ans": "B"
  },
  {
    "num": 30,
    "origNum": 44,
    "category": "Grammar",
    "unit": "8B",
    "topic": "Past simple: positive",
    "q": "\"The bear _______ around the garden.\"",
    "a": "walk",
    "b": "walks",
    "c": "walked",
    "d": "walking",
    "ans": "C"
  },
  {
    "num": 31,
    "origNum": 45,
    "category": "Grammar",
    "unit": "8B",
    "topic": "Past simple: positive",
    "q": "\"They _______ to catch the deer.\"",
    "a": "come",
    "b": "comes",
    "c": "came",
    "d": "coming",
    "ans": "C"
  },
  {
    "num": 32,
    "origNum": 49,
    "category": "Vocabulary",
    "unit": "8B",
    "topic": "Animals",
    "q": "How many deer were in the woman's flat?",
    "a": "one",
    "b": "two",
    "c": "three",
    "d": "four",
    "ans": "C"
  },
  {
    "num": 33,
    "origNum": 50,
    "category": "Grammar",
    "unit": "8B",
    "topic": "Past simple: positive",
    "q": "\"The hippos _______ some grass and then _______ away.\"",
    "a": "eat / go",
    "b": "ate / went",
    "c": "eats / goes",
    "d": "eating / going",
    "ans": "B"
  },
  {
    "num": 34,
    "origNum": 51,
    "category": "Grammar",
    "unit": "8B",
    "topic": "Past simple: positive",
    "q": "\"He _______ something strange in the garden.\"",
    "a": "hear",
    "b": "hears",
    "c": "heard",
    "d": "hearing",
    "ans": "C"
  },
  {
    "num": 35,
    "origNum": 53,
    "category": "Grammar",
    "unit": "9A",
    "topic": "Past simple: negative",
    "q": "\"We _______ go to big cities.\" Complete with the negative past simple.",
    "a": "don't",
    "b": "doesn't",
    "c": "didn't",
    "d": "wasn't",
    "ans": "C"
  },
  {
    "num": 36,
    "origNum": 54,
    "category": "Grammar",
    "unit": "9A",
    "topic": "Past simple: negative",
    "q": "\"We _______ stay in a hotel.\" (negative)",
    "a": "don't",
    "b": "didn't",
    "c": "doesn't",
    "d": "weren't",
    "ans": "B"
  },
  {
    "num": 37,
    "origNum": 55,
    "category": "Grammar",
    "unit": "9A",
    "topic": "Past simple: negative",
    "q": "The past simple negative is formed with: subject + _______ + base verb.",
    "a": "don't",
    "b": "doesn't",
    "c": "didn't",
    "d": "wasn't",
    "ans": "C"
  },
  {
    "num": 38,
    "origNum": 56,
    "category": "Grammar",
    "unit": "9A",
    "topic": "Past simple: negative",
    "q": "\"We _______ have a car.\" (negative past)",
    "a": "don't",
    "b": "didn't",
    "c": "doesn't",
    "d": "haven't",
    "ans": "B"
  },
  {
    "num": 39,
    "origNum": 57,
    "category": "Grammar",
    "unit": "9A",
    "topic": "Past simple: negative",
    "q": "Which sentence is correct?",
    "a": "I didn't stayed in a hotel.",
    "b": "I didn't stay in a hotel.",
    "c": "I didn't stays in a hotel.",
    "d": "I not stay in a hotel.",
    "ans": "B"
  },
  {
    "num": 40,
    "origNum": 63,
    "category": "Grammar",
    "unit": "9B",
    "topic": "Past simple: questions",
    "q": "\"_______ you at work yesterday?\"",
    "a": "Did",
    "b": "Do",
    "c": "Were",
    "d": "Are",
    "ans": "C"
  },
  {
    "num": 41,
    "origNum": 64,
    "category": "Grammar",
    "unit": "9B",
    "topic": "Past simple: questions",
    "q": "\"How _______ you get there?\"",
    "a": "do",
    "b": "did",
    "c": "was",
    "d": "were",
    "ans": "B"
  },
  {
    "num": 42,
    "origNum": 65,
    "category": "Grammar",
    "unit": "9B",
    "topic": "Past simple: questions",
    "q": "\"_______ you enjoy it there?\" \"Yes, I did.\"",
    "a": "Do",
    "b": "Are",
    "c": "Did",
    "d": "Were",
    "ans": "C"
  },
  {
    "num": 43,
    "origNum": 66,
    "category": "Grammar",
    "unit": "9B",
    "topic": "Past simple: questions",
    "q": "Which question is grammatically correct?",
    "a": "Where did you went?",
    "b": "Where did you go?",
    "c": "Where you did go?",
    "d": "Where do you went?",
    "ans": "B"
  },
  {
    "num": 44,
    "origNum": 67,
    "category": "Vocabulary",
    "unit": "9B",
    "topic": "Seasons",
    "q": "Which season comes after summer?",
    "a": "spring",
    "b": "winter",
    "c": "autumn",
    "d": "summer",
    "ans": "C"
  },
  {
    "num": 45,
    "origNum": 68,
    "category": "Vocabulary",
    "unit": "9B",
    "topic": "Weather",
    "q": "The weather in New York in December was:",
    "a": "hot and sunny",
    "b": "cold and windy",
    "c": "warm and dry",
    "d": "cool and rainy",
    "ans": "B"
  },
  {
    "num": 46,
    "origNum": 69,
    "category": "Vocabulary",
    "unit": "9B",
    "topic": "Weather",
    "q": "\"It was very cold and _______. Everyone stayed inside.\"",
    "a": "sunny",
    "b": "hot",
    "c": "snowy",
    "d": "windy",
    "ans": "C"
  }
];

// Article questions temporarily removed as requested
const BEGINNER2_ARTICLE = [];

// ===== ADVANCED 1 MCQ QUESTIONS (50 Questions) =====
// Units 2A, 2B, 3A, 3B, 4A, 4B
const ADVANCED1_MCQ = [
  { "num": 1, "category": "Grammar", "unit": "2A", "topic": "Present perfect vs past simple", "q": "\"I _______ for the job last Monday.\" Choose the correct form.", "a": "have applied", "b": "applied", "c": "was applying", "d": "had applied", "ans": "B" },
  { "num": 2, "category": "Grammar", "unit": "2A", "topic": "Present perfect vs past simple", "q": "\"They've just _______ me the job.\" Choose the correct form.", "a": "offer", "b": "offering", "c": "offered", "d": "offers", "ans": "C" },
  { "num": 3, "category": "Grammar", "unit": "2A", "topic": "Present perfect vs past simple", "q": "Which tense do we use to talk about events at a particular time in the past?", "a": "present perfect", "b": "past simple", "c": "past continuous", "d": "present perfect continuous", "ans": "B" },
  { "num": 4, "category": "Grammar", "unit": "2A", "topic": "Present perfect vs past simple", "q": "Which tense do we use to talk about recent events that have an effect on the present?", "a": "past simple", "b": "past continuous", "c": "present perfect", "d": "past perfect", "ans": "C" },
  { "num": 5, "category": "Vocabulary", "unit": "2A", "topic": "Work", "q": "A document that describes your education and the jobs you have had is called a:", "a": "career", "b": "CV", "c": "contract", "d": "diploma", "ans": "B" },
  { "num": 6, "category": "Vocabulary", "unit": "2A", "topic": "Work", "q": "\"People who are trying to get a job\" are called:", "a": "employees", "b": "employers", "c": "candidates", "d": "colleagues", "ans": "C" },
  { "num": 7, "category": "Vocabulary", "unit": "2A", "topic": "Work", "q": "\"The people you work for\" are your:", "a": "candidates", "b": "contacts", "c": "colleagues", "d": "employers", "ans": "D" },
  { "num": 8, "category": "Grammar", "unit": "2A", "topic": "Present perfect vs past simple", "q": "\"I _______ (never / have) a really terrible job interview.\" Complete with the correct form.", "a": "never had", "b": "have never had", "c": "never have", "d": "was never having", "ans": "B" },
  { "num": 9, "category": "Grammar", "unit": "2A", "topic": "Present perfect vs past simple", "q": "\"Once, I _______ (forget) to turn off my phone at the cinema.\"", "a": "have forgotten", "b": "forgot", "c": "was forgetting", "d": "had forgotten", "ans": "B" },
  { "num": 10, "category": "Grammar", "unit": "2A", "topic": "Present perfect", "q": "\"I _______ (already / work) for more than three organisations.\"", "a": "already worked", "b": "was already working", "c": "have already worked", "d": "had already worked", "ans": "C" },
  { "num": 11, "category": "Vocabulary", "unit": "2A", "topic": "Work", "q": "Being \"in charge of\" a team means you are:", "a": "a new member", "b": "responsible for the team", "c": "a candidate for the team", "d": "leaving the team", "ans": "B" },
  { "num": 12, "category": "Grammar", "unit": "2A", "topic": "Present perfect vs past simple", "q": "\"I _______ (finish) my exams, but I _______ (not / get) the results yet.\"", "a": "finished / didn't get", "b": "have finished / haven't got", "c": "finish / don't get", "d": "had finished / hadn't got", "ans": "B" },
  { "num": 13, "category": "Vocabulary", "unit": "2B", "topic": "Technology", "q": "A small computer program that you can download onto a mobile phone is called:", "a": "a browser", "b": "an icon", "c": "an app", "d": "a username", "ans": "C" },
  { "num": 14, "category": "Vocabulary", "unit": "2B", "topic": "Technology", "q": "A computer program that you use to read information on the Internet is called:", "a": "an app", "b": "a browser", "c": "an icon", "d": "a text message", "ans": "B" },
  { "num": 15, "category": "Vocabulary", "unit": "2B", "topic": "Technology", "q": "Which verb does NOT go with \"a video\"?", "a": "download", "b": "press", "c": "share", "d": "upload", "ans": "B" },
  { "num": 16, "category": "Grammar", "unit": "2B", "topic": "Present perfect continuous", "q": "\"I've been _______ photos since I was 12.\" Complete with the correct form.", "a": "take", "b": "took", "c": "taking", "d": "taken", "ans": "C" },
  { "num": 17, "category": "Grammar", "unit": "2B", "topic": "Present perfect continuous", "q": "\"I _______ this phone for three years.\" Choose the correct form. (own)", "a": "have been owning", "b": "have owned", "c": "am owning", "d": "owned", "ans": "B" },
  { "num": 18, "category": "Grammar", "unit": "2B", "topic": "Present perfect continuous", "q": "We use the present perfect continuous for:", "a": "finished actions", "b": "activities that started in the past and are still continuing", "c": "future plans", "d": "single past events", "ans": "B" },
  { "num": 19, "category": "Grammar", "unit": "2B", "topic": "Present perfect continuous", "q": "\"I _______ TV all day.\" (watch) Choose the correct continuous form.", "a": "watched", "b": "have watched", "c": "have been watching", "d": "was watching", "ans": "C" },
  { "num": 20, "category": "Grammar", "unit": "2B", "topic": "Present perfect continuous", "q": "\"I _______ for a new tablet, but I haven't got enough money yet.\" (save up)", "a": "saved up", "b": "have been saving up", "c": "am saving up", "d": "was saving up", "ans": "B" },
  { "num": 21, "category": "Vocabulary", "unit": "2B", "topic": "Technology", "q": "A small picture on a screen that you click on to open a program is called:", "a": "an app", "b": "a browser", "c": "an icon", "d": "a username", "ans": "C" },
  { "num": 22, "category": "Grammar", "unit": "2B", "topic": "Present perfect vs continuous", "q": "We use the present perfect simple (NOT continuous) with _______ verbs like \"own\", \"know\", \"be\".", "a": "action", "b": "state", "c": "modal", "d": "phrasal", "ans": "B" },
  { "num": 23, "category": "Vocabulary", "unit": "3A", "topic": "Relationships", "q": "\"To find out what someone is really like\" means to:", "a": "keep in touch", "b": "get to know", "c": "get on well", "d": "have in common", "ans": "B" },
  { "num": 24, "category": "Vocabulary", "unit": "3A", "topic": "Relationships", "q": "\"My sister and I have a lot in common.\" This means they:", "a": "argue a lot", "b": "live together", "c": "share the same interests", "d": "work together", "ans": "C" },
  { "num": 25, "category": "Vocabulary", "unit": "3A", "topic": "Relationships", "q": "\"I'm not very good at _______ with friends when they move far away.\"", "a": "getting on", "b": "keeping in touch", "c": "getting to know", "d": "growing up", "ans": "B" },
  { "num": 26, "category": "Grammar", "unit": "3A", "topic": "Narrative tenses", "q": "\"Rosalind _______ in a retirement community in Florida.\" Which tense describes the background?", "a": "lived", "b": "was living", "c": "had lived", "d": "has lived", "ans": "B" },
  { "num": 27, "category": "Grammar", "unit": "3A", "topic": "Narrative tenses", "q": "\"She _______ there 20 years earlier.\" Which tense refers to an action before another past action?", "a": "moved", "b": "was moving", "c": "has moved", "d": "had moved", "ans": "D" },
  { "num": 28, "category": "Grammar", "unit": "3A", "topic": "Narrative tenses", "q": "The past perfect is formed with:", "a": "was/were + verb-ing", "b": "had + past participle", "c": "has/have + past participle", "d": "did + base form", "ans": "B" },
  { "num": 29, "category": "Grammar", "unit": "3A", "topic": "Narrative tenses", "q": "\"Many newspapers _______ the story.\" Choose the correct past simple form.", "a": "reported", "b": "were reporting", "c": "had reported", "d": "have reported", "ans": "A" },
  { "num": 30, "category": "Grammar", "unit": "3A", "topic": "Narrative tenses", "q": "\"I _______ (meet) my friend Amy in 2015.\" What is the correct tense?", "a": "have met", "b": "was meeting", "c": "met", "d": "had met", "ans": "C" },
  { "num": 31, "category": "Vocabulary", "unit": "3A", "topic": "Relationships", "q": "\"To like someone and enjoy being with them\" means to:", "a": "get to know them", "b": "keep in touch", "c": "get on well with them", "d": "come from the same background", "ans": "C" },
  { "num": 32, "category": "Vocabulary", "unit": "3A", "topic": "Relationships", "q": "\"To grow up in the same kind of family and/or social group\" means to:", "a": "get on well", "b": "have in common", "c": "come from the same background", "d": "keep in touch", "ans": "C" },
  { "num": 33, "category": "Vocabulary", "unit": "3B", "topic": "Multi-word verbs", "q": "\"I mainly _______ my dad.\" means \"I am similar to my dad.\"", "a": "take after", "b": "grow apart", "c": "bring up", "d": "get on with", "ans": "A" },
  { "num": 34, "category": "Vocabulary", "unit": "3B", "topic": "Multi-word verbs", "q": "\"We started to _______.\" means their relationship became less close.", "a": "cut off", "b": "hang out", "c": "grow apart", "d": "take after", "ans": "C" },
  { "num": 35, "category": "Vocabulary", "unit": "3B", "topic": "Multi-word verbs", "q": "\"To look after a child until they are an adult\" means to:", "a": "grow up", "b": "take after", "c": "bring up", "d": "grow apart", "ans": "C" },
  { "num": 36, "category": "Grammar", "unit": "3B", "topic": "used to", "q": "\"We _______ wear different clothes.\" Choose the correct form for a past habit.", "a": "use to", "b": "used to", "c": "are used to", "d": "were using to", "ans": "B" },
  { "num": 37, "category": "Grammar", "unit": "3B", "topic": "used to", "q": "We use \"used to\" + infinitive to talk about:", "a": "current habits", "b": "future plans", "c": "past habits and states", "d": "single past events", "ans": "C" },
  { "num": 38, "category": "Grammar", "unit": "3B", "topic": "used to", "q": "Which word do we use with the present simple to talk about current habits?", "a": "used to", "b": "always", "c": "usually", "d": "Both B and C", "ans": "D" },
  { "num": 39, "category": "Grammar", "unit": "3B", "topic": "used to", "q": "\"My parents didn't _______ let me stay up late.\" Complete the negative form.", "a": "used to", "b": "use to", "c": "using to", "d": "uses to", "ans": "B" },
  { "num": 40, "category": "Vocabulary", "unit": "3B", "topic": "Multi-word verbs", "q": "\"We usually get _______ once or twice a week.\" means \"We meet up.\"", "a": "on", "b": "together", "c": "apart", "d": "after", "ans": "B" },
  { "num": 41, "category": "Grammar", "unit": "4A", "topic": "Modals of ability", "q": "\"Tsung Tsung _______ play the piano when he was three.\"", "a": "can", "b": "could", "c": "was able to", "d": "managed to", "ans": "B" },
  { "num": 42, "category": "Grammar", "unit": "4A", "topic": "Modals of ability", "q": "\"He said his dream was _______ play like Mozart.\"", "a": "could", "b": "can", "c": "to be able to", "d": "manage to", "ans": "C" },
  { "num": 43, "category": "Grammar", "unit": "4A", "topic": "Modals of ability", "q": "The verb \"manage to\" means:", "a": "to have a general ability", "b": "to succeed in doing something difficult", "c": "to be unable to do something", "d": "to want to do something", "ans": "B" },
  { "num": 44, "category": "Grammar", "unit": "4A", "topic": "Modals of ability", "q": "\"I've _______ ski since I was five years old.\"", "a": "could", "b": "can", "c": "been able to", "d": "managed to", "ans": "C" },
  { "num": 45, "category": "Grammar", "unit": "4A", "topic": "Modals of ability", "q": "We can't say \"will can\", so instead we say:", "a": "will could", "b": "will be able to", "c": "will manage", "d": "would can", "ans": "B" },
  { "num": 46, "category": "Vocabulary", "unit": "4B", "topic": "Personality adjectives", "q": "Which adjective describes someone who \"likes being with other people\"?", "a": "shy", "b": "reserved", "c": "sociable", "d": "sensitive", "ans": "C" },
  { "num": 47, "category": "Vocabulary", "unit": "4B", "topic": "Personality adjectives", "q": "Someone who is \"quiet and doesn't laugh a lot\" is:", "a": "outgoing", "b": "lively", "c": "talkative", "d": "serious", "ans": "D" },
  { "num": 48, "category": "Grammar", "unit": "4B", "topic": "Articles", "q": "We use \"a/an\" when we mention a person or thing for the _______ time.", "a": "second", "b": "last", "c": "first", "d": "same", "ans": "C" },
  { "num": 49, "category": "Grammar", "unit": "4B", "topic": "Articles", "q": "\"I'm going to _______ supermarket.\" Which article fills the gap?", "a": "a", "b": "an", "c": "the", "d": "no article", "ans": "C" },
  { "num": 50, "category": "Grammar", "unit": "4B", "topic": "Articles", "q": "\"I never play _______ video games.\" Which is correct?", "a": "a", "b": "an", "c": "the", "d": "no article", "ans": "D" }
];

const LEVELS = [
  { id: 'beginner1', name: 'Beginner 1', desc: 'Basics of English – alphabet, greetings, simple present', icon: '🌱', color: '#27ae60', locked: true },
  { id: 'beginner2', name: 'Beginner 2', desc: 'Grammar & Vocabulary – Units 7-9: demonstratives, clothes, past simple', icon: '📘', color: '#2e75b6', locked: false, questionsCount: 46 },
  { id: 'elementary1', name: 'Elementary 1', desc: 'Expanding grammar – comparatives, modals, present continuous', icon: '📗', color: '#8e44ad', locked: true },
  { id: 'elementary2', name: 'Elementary 2', desc: 'Intermediate grammar – future tenses, conditionals', icon: '📙', color: '#e67e22', locked: true },
  { id: 'advanced1', name: 'Advanced 1', desc: 'Units 2-4: present perfect, narrative tenses, modals, multi-word verbs, articles', icon: '🔥', color: '#e74c3c', locked: false, questionsCount: 50 },
  { id: 'preintermediate', name: 'Pre-Intermediate', desc: 'Complex structures – passive voice, reported speech', icon: '📕', color: '#c0392b', locked: true },
  { id: 'intermediate', name: 'Intermediate', desc: 'Advanced topics – idioms, phrasal verbs, essay writing', icon: '🎓', color: '#2c3e50', locked: true }
];
