// ===== BEGINNER 2 APPROVED MCQ QUESTIONS (46 Questions) =====
// Filtered according to feedback from Questions_100.xlsx

const BEGINNER2_MCQ = [
  {
    "num": 1,
    "origNum": 1,
    "category": "Grammar",
    "unit": "7A",
    "topic": "this/that/these/those",
    "q": "Complete: \"I like _______ plant.\" (pointing to a plant near you)",
    "a": "this",
    "b": "that",
    "c": "these",
    "d": "those",
    "ans": "A"
  },
  {
    "num": 2,
    "origNum": 2,
    "category": "Grammar",
    "unit": "7A",
    "topic": "this/that/these/those",
    "q": "Complete: \"Oh, look at _______ chairs over there. They're really nice.\"",
    "a": "this",
    "b": "that",
    "c": "these",
    "d": "those",
    "ans": "D"
  },
  {
    "num": 3,
    "origNum": 3,
    "category": "Grammar",
    "unit": "7A",
    "topic": "this/that/these/those",
    "q": "Which word is used for a singular object far from the speaker?",
    "a": "this",
    "b": "that",
    "c": "these",
    "d": "those",
    "ans": "B"
  },
  {
    "num": 4,
    "origNum": 4,
    "category": "Grammar",
    "unit": "7A",
    "topic": "this/that/these/those",
    "q": "Which word is used for plural objects near the speaker?",
    "a": "this",
    "b": "that",
    "c": "these",
    "d": "those",
    "ans": "C"
  },
  {
    "num": 5,
    "origNum": 5,
    "category": "Grammar",
    "unit": "7A",
    "topic": "this/that/these/those",
    "q": "\"_______ plates are beautiful!\" (pointing to plates far away)",
    "a": "This",
    "b": "That",
    "c": "These",
    "d": "Those",
    "ans": "D"
  },
  {
    "num": 6,
    "origNum": 6,
    "category": "Grammar",
    "unit": "7A",
    "topic": "this/that/these/those",
    "q": "\"Look at _______ speaker! That's so cool.\" (pointing to a speaker far away)",
    "a": "this",
    "b": "that",
    "c": "these",
    "d": "those",
    "ans": "B"
  },
  {
    "num": 7,
    "origNum": 9,
    "category": "Vocabulary",
    "unit": "7A",
    "topic": "Prices",
    "q": "How do you correctly say \"£3.80\" in English?",
    "a": "three pound eighty",
    "b": "three pounds and eighty",
    "c": "three pounds eighty",
    "d": "three and eighty pounds",
    "ans": "C"
  },
  {
    "num": 8,
    "origNum": 12,
    "category": "Vocabulary",
    "unit": "7A",
    "topic": "Shopping",
    "q": "What time does Books & Co. open?",
    "a": "8 am",
    "b": "6 am",
    "c": "9 am",
    "d": "10 am",
    "ans": "C"
  },
  {
    "num": 9,
    "origNum": 13,
    "category": "Grammar",
    "unit": "7A",
    "topic": "this/that/these/those",
    "q": "\"_______ lamp is nice – it's a great colour!\" (holding a lamp near you)",
    "a": "This",
    "b": "That",
    "c": "These",
    "d": "Those",
    "ans": "A"
  },
  {
    "num": 10,
    "origNum": 14,
    "category": "Vocabulary",
    "unit": "7A",
    "topic": "Sounds/Spelling",
    "q": "Which word has the /b/ sound?",
    "a": "plate",
    "b": "guitar",
    "c": "bag",
    "d": "cup",
    "ans": "C"
  },
  {
    "num": 11,
    "origNum": 15,
    "category": "Grammar",
    "unit": "7B",
    "topic": "Possessive 's",
    "q": "\"Is this Greg's T-shirt?\" means:",
    "a": "The T-shirt belongs to Greg",
    "b": "Greg is a T-shirt",
    "c": "Greg bought a T-shirt for someone",
    "d": "The T-shirt is new",
    "ans": "A"
  },
  {
    "num": 12,
    "origNum": 16,
    "category": "Grammar",
    "unit": "7B",
    "topic": "Possessive 's",
    "q": "\"They're Kate's jeans.\" What does \"Kate's\" mean?",
    "a": "Kate is jeans",
    "b": "The jeans belong to Kate",
    "c": "Kate likes jeans",
    "d": "Kate sells jeans",
    "ans": "B"
  },
  {
    "num": 13,
    "origNum": 17,
    "category": "Grammar",
    "unit": "7B",
    "topic": "Adverbs of frequency",
    "q": "Which adverb means \"100% of the time\"?",
    "a": "sometimes",
    "b": "often",
    "c": "usually",
    "d": "always",
    "ans": "D"
  },
  {
    "num": 14,
    "origNum": 18,
    "category": "Grammar",
    "unit": "7B",
    "topic": "Adverbs of frequency",
    "q": "\"She wears a skirt (never).\" The correct sentence is:",
    "a": "She never wears a skirt.",
    "b": "She wears never a skirt.",
    "c": "Never she wears a skirt.",
    "d": "She wears a skirt never.",
    "ans": "A"
  },
  {
    "num": 15,
    "origNum": 19,
    "category": "Grammar",
    "unit": "7B",
    "topic": "Adverbs of frequency",
    "q": "\"Fran wears a dress (often).\" The correct sentence is:",
    "a": "Often Fran wears a dress.",
    "b": "Fran wears often a dress.",
    "c": "Fran often wears a dress.",
    "d": "Fran wears a dress often.",
    "ans": "C"
  },
  {
    "num": 16,
    "origNum": 21,
    "category": "Vocabulary",
    "unit": "7B",
    "topic": "Clothes",
    "q": "Tom Ford often wears a _______ shirt.",
    "a": "black",
    "b": "blue",
    "c": "white",
    "d": "red",
    "ans": "C"
  },
  {
    "num": 17,
    "origNum": 28,
    "category": "Grammar",
    "unit": "8A",
    "topic": "Past simple: be",
    "q": "Complete: \"I _______ in New York three days ago.\"",
    "a": "am",
    "b": "was",
    "c": "were",
    "d": "be",
    "ans": "B"
  },
  {
    "num": 18,
    "origNum": 29,
    "category": "Grammar",
    "unit": "8A",
    "topic": "Past simple: be",
    "q": "Complete: \"We _______ in Munich on Wednesday.\"",
    "a": "was",
    "b": "am",
    "c": "were",
    "d": "is",
    "ans": "C"
  },
  {
    "num": 19,
    "origNum": 30,
    "category": "Grammar",
    "unit": "8A",
    "topic": "Past simple: be",
    "q": "\"_______ you at work yesterday?\" Complete with the correct form.",
    "a": "Was",
    "b": "Were",
    "c": "Are",
    "d": "Is",
    "ans": "B"
  },
  {
    "num": 20,
    "origNum": 31,
    "category": "Grammar",
    "unit": "8A",
    "topic": "Past simple: be negative",
    "q": "\"It _______ a holiday for me.\" (negative)",
    "a": "wasn't",
    "b": "weren't",
    "c": "isn't",
    "d": "didn't",
    "ans": "A"
  },
  {
    "num": 21,
    "origNum": 32,
    "category": "Grammar",
    "unit": "8A",
    "topic": "Past simple: be negative",
    "q": "\"We _______ at the party last night.\" (negative)",
    "a": "wasn't",
    "b": "weren't",
    "c": "didn't",
    "d": "aren't",
    "ans": "B"
  },
  {
    "num": 22,
    "origNum": 33,
    "category": "Grammar",
    "unit": "8A",
    "topic": "Past simple: be",
    "q": "Which sentence is correct?",
    "a": "She were in Dublin.",
    "b": "They was at home.",
    "c": "He was at a meeting.",
    "d": "I were in London.",
    "ans": "C"
  },
  {
    "num": 23,
    "origNum": 34,
    "category": "Vocabulary",
    "unit": "8A",
    "topic": "Past time expressions",
    "q": "Which expression means \"the day before today\"?",
    "a": "last week",
    "b": "two days ago",
    "c": "yesterday",
    "d": "this morning",
    "ans": "C"
  },
  {
    "num": 24,
    "origNum": 35,
    "category": "Vocabulary",
    "unit": "8A",
    "topic": "Past time expressions",
    "q": "\"Two weeks _______\" – complete the expression.",
    "a": "before",
    "b": "ago",
    "c": "past",
    "d": "last",
    "ans": "B"
  },
  {
    "num": 25,
    "origNum": 39,
    "category": "Vocabulary",
    "unit": "8A",
    "topic": "Events",
    "q": "Ava was on tour with her _______.",
    "a": "football team",
    "b": "band",
    "c": "photography group",
    "d": "family",
    "ans": "B"
  },
  {
    "num": 26,
    "origNum": 40,
    "category": "Grammar",
    "unit": "8A",
    "topic": "Past simple: be",
    "q": "\"About 1,000 people _______ at our concert.\"",
    "a": "was",
    "b": "is",
    "c": "were",
    "d": "are",
    "ans": "C"
  },
  {
    "num": 27,
    "origNum": 41,
    "category": "Vocabulary",
    "unit": "8A",
    "topic": "Adjectives",
    "q": "Match: \"The meeting was _______.\" Which adjective is used in the text?",
    "a": "boring",
    "b": "interesting",
    "c": "exciting",
    "d": "fun",
    "ans": "B"
  },
  {
    "num": 28,
    "origNum": 42,
    "category": "Grammar",
    "unit": "8B",
    "topic": "Past simple: positive",
    "q": "\"He _______ a bear in the garden.\" Choose the correct past simple form.",
    "a": "see",
    "b": "sees",
    "c": "saw",
    "d": "seen",
    "ans": "C"
  },
  {
    "num": 29,
    "origNum": 43,
    "category": "Grammar",
    "unit": "8B",
    "topic": "Past simple: positive",
    "q": "\"She _______ into her living room and _______ TV.\"",
    "a": "go / watch",
    "b": "went / watched",
    "c": "goes / watches",
    "d": "going / watching",
    "ans": "B"
  },
  {
    "num": 30,
    "origNum": 44,
    "category": "Grammar",
    "unit": "8B",
    "topic": "Past simple: positive",
    "q": "\"The bear _______ around the garden.\"",
    "a": "walk",
    "b": "walks",
    "c": "walked",
    "d": "walking",
    "ans": "C"
  },
  {
    "num": 31,
    "origNum": 45,
    "category": "Grammar",
    "unit": "8B",
    "topic": "Past simple: positive",
    "q": "\"They _______ to catch the deer.\"",
    "a": "come",
    "b": "comes",
    "c": "came",
    "d": "coming",
    "ans": "C"
  },
  {
    "num": 32,
    "origNum": 49,
    "category": "Vocabulary",
    "unit": "8B",
    "topic": "Animals",
    "q": "How many deer were in the woman's flat?",
    "a": "one",
    "b": "two",
    "c": "three",
    "d": "four",
    "ans": "C"
  },
  {
    "num": 33,
    "origNum": 50,
    "category": "Grammar",
    "unit": "8B",
    "topic": "Past simple: positive",
    "q": "\"The hippos _______ some grass and then _______ away.\"",
    "a": "eat / go",
    "b": "ate / went",
    "c": "eats / goes",
    "d": "eating / going",
    "ans": "B"
  },
  {
    "num": 34,
    "origNum": 51,
    "category": "Grammar",
    "unit": "8B",
    "topic": "Past simple: positive",
    "q": "\"He _______ something strange in the garden.\"",
    "a": "hear",
    "b": "hears",
    "c": "heard",
    "d": "hearing",
    "ans": "C"
  },
  {
    "num": 35,
    "origNum": 53,
    "category": "Grammar",
    "unit": "9A",
    "topic": "Past simple: negative",
    "q": "\"We _______ go to big cities.\" Complete with the negative past simple.",
    "a": "don't",
    "b": "doesn't",
    "c": "didn't",
    "d": "wasn't",
    "ans": "C"
  },
  {
    "num": 36,
    "origNum": 54,
    "category": "Grammar",
    "unit": "9A",
    "topic": "Past simple: negative",
    "q": "\"We _______ stay in a hotel.\" (negative)",
    "a": "don't",
    "b": "didn't",
    "c": "doesn't",
    "d": "weren't",
    "ans": "B"
  },
  {
    "num": 37,
    "origNum": 55,
    "category": "Grammar",
    "unit": "9A",
    "topic": "Past simple: negative",
    "q": "The past simple negative is formed with: subject + _______ + base verb.",
    "a": "don't",
    "b": "doesn't",
    "c": "didn't",
    "d": "wasn't",
    "ans": "C"
  },
  {
    "num": 38,
    "origNum": 56,
    "category": "Grammar",
    "unit": "9A",
    "topic": "Past simple: negative",
    "q": "\"We _______ have a car.\" (negative past)",
    "a": "don't",
    "b": "didn't",
    "c": "doesn't",
    "d": "haven't",
    "ans": "B"
  },
  {
    "num": 39,
    "origNum": 57,
    "category": "Grammar",
    "unit": "9A",
    "topic": "Past simple: negative",
    "q": "Which sentence is correct?",
    "a": "I didn't stayed in a hotel.",
    "b": "I didn't stay in a hotel.",
    "c": "I didn't stays in a hotel.",
    "d": "I not stay in a hotel.",
    "ans": "B"
  },
  {
    "num": 40,
    "origNum": 63,
    "category": "Grammar",
    "unit": "9B",
    "topic": "Past simple: questions",
    "q": "\"_______ you at work yesterday?\"",
    "a": "Did",
    "b": "Do",
    "c": "Were",
    "d": "Are",
    "ans": "C"
  },
  {
    "num": 41,
    "origNum": 64,
    "category": "Grammar",
    "unit": "9B",
    "topic": "Past simple: questions",
    "q": "\"How _______ you get there?\"",
    "a": "do",
    "b": "did",
    "c": "was",
    "d": "were",
    "ans": "B"
  },
  {
    "num": 42,
    "origNum": 65,
    "category": "Grammar",
    "unit": "9B",
    "topic": "Past simple: questions",
    "q": "\"_______ you enjoy it there?\" \"Yes, I did.\"",
    "a": "Do",
    "b": "Are",
    "c": "Did",
    "d": "Were",
    "ans": "C"
  },
  {
    "num": 43,
    "origNum": 66,
    "category": "Grammar",
    "unit": "9B",
    "topic": "Past simple: questions",
    "q": "Which question is grammatically correct?",
    "a": "Where did you went?",
    "b": "Where did you go?",
    "c": "Where you did go?",
    "d": "Where do you went?",
    "ans": "B"
  },
  {
    "num": 44,
    "origNum": 67,
    "category": "Vocabulary",
    "unit": "9B",
    "topic": "Seasons",
    "q": "Which season comes after summer?",
    "a": "spring",
    "b": "winter",
    "c": "autumn",
    "d": "summer",
    "ans": "C"
  },
  {
    "num": 45,
    "origNum": 68,
    "category": "Vocabulary",
    "unit": "9B",
    "topic": "Weather",
    "q": "The weather in New York in December was:",
    "a": "hot and sunny",
    "b": "cold and windy",
    "c": "warm and dry",
    "d": "cool and rainy",
    "ans": "B"
  },
  {
    "num": 46,
    "origNum": 69,
    "category": "Vocabulary",
    "unit": "9B",
    "topic": "Weather",
    "q": "\"It was very cold and _______. Everyone stayed inside.\"",
    "a": "sunny",
    "b": "hot",
    "c": "snowy",
    "d": "windy",
    "ans": "C"
  }
];

// Article questions temporarily removed as requested
const BEGINNER2_ARTICLE = [];

const LEVELS = [
  { id: 'beginner1', name: 'Beginner 1', desc: 'Basics of English – alphabet, greetings, simple present', icon: '🌱', color: '#27ae60', locked: true },
  { id: 'beginner2', name: 'Beginner 2', desc: 'Grammar & Vocabulary – Units 7-9: demonstratives, clothes, past simple', icon: '📘', color: '#2e75b6', locked: false, questionsCount: 46 },
  { id: 'elementary1', name: 'Elementary 1', desc: 'Expanding grammar – comparatives, modals, present continuous', icon: '📗', color: '#8e44ad', locked: true },
  { id: 'elementary2', name: 'Elementary 2', desc: 'Intermediate grammar – future tenses, conditionals', icon: '📙', color: '#e67e22', locked: true },
  { id: 'preintermediate', name: 'Pre-Intermediate', desc: 'Complex structures – passive voice, reported speech', icon: '📕', color: '#e74c3c', locked: true },
  { id: 'intermediate', name: 'Intermediate', desc: 'Advanced topics – idioms, phrasal verbs, essay writing', icon: '🎓', color: '#2c3e50', locked: true }
];
